import { useIncidentStore } from '@/stores/incidentStore'
import { BookOpen, ChevronRight, RotateCcw } from 'lucide-react'
import { motion } from 'framer-motion'
import clsx from 'clsx'
import type { RiskLevel, RunbookStepStatus } from '@/types/causal'

const RISK: Record<RiskLevel, string> = {
  Low:      'bg-emerald-900/30 text-emerald-300 border-emerald-600/30',
  Medium:   'bg-amber-900/30  text-amber-300   border-amber-600/30',
  High:     'bg-orange-900/40 text-orange-300  border-orange-600/40',
  Critical: 'bg-red-900/50    text-red-300     border-red-600/50',
}

const STEP_STATUS: Record<RunbookStepStatus, { cls: string; dot: string }> = {
  pending:   { cls: 'text-gray-600',     dot: 'bg-gray-700' },
  approved:  { cls: 'text-blue-400',     dot: 'bg-blue-500' },
  running:   { cls: 'text-amber-400',    dot: 'bg-amber-400 animate-pulse' },
  completed: { cls: 'text-emerald-400',  dot: 'bg-emerald-500' },
  failed:    { cls: 'text-red-400',      dot: 'bg-red-500' },
  rejected:  { cls: 'text-orange-400',   dot: 'bg-orange-500' },
}

export function RunbookViewer() {
  const { runbook } = useIncidentStore()

  if (!runbook) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-2 text-gray-700 py-6">
        <BookOpen size={22} className="opacity-40" />
        <p className="text-[11px] text-center leading-relaxed">
          Runbook generated by<br />Remediation Agent
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-1.5">
      <p className="text-[10px] font-semibold text-gray-400 px-0.5 mb-2 truncate">{runbook.title}</p>
      {runbook.steps.map((step, i) => {
        const ss = STEP_STATUS[step.status] ?? STEP_STATUS.pending
        return (
          <motion.div
            key={step.step}
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.04 }}
            className="rounded-lg border border-gray-800 bg-gray-800/40 p-2.5"
          >
            <div className="flex items-start gap-2">
              {/* Step number + status dot */}
              <div className="flex flex-col items-center gap-1 shrink-0 pt-0.5">
                <span className="text-[9px] font-mono text-gray-600 leading-none">
                  {step.step.toString().padStart(2, '0')}
                </span>
                <span className={clsx('w-1.5 h-1.5 rounded-full', ss.dot)} />
              </div>

              <div className="flex-1 min-w-0">
                {/* Action + risk */}
                <div className="flex items-start gap-1.5 flex-wrap mb-1">
                  <span className="text-[11px] font-medium text-gray-200 leading-tight flex-1 min-w-0">
                    {step.action}
                  </span>
                  <span className={clsx('text-[9px] px-1.5 py-0.5 rounded border shrink-0 font-semibold', RISK[step.risk])}>
                    {step.risk}
                  </span>
                </div>

                {/* Description */}
                <p className="text-[10px] text-gray-500 leading-relaxed mb-1">{step.description}</p>

                {/* Expected outcome */}
                <div className="flex items-center gap-1 text-[10px] text-gray-600">
                  <ChevronRight size={9} className="shrink-0" />
                  <span className="truncate">{step.expected_outcome}</span>
                </div>

                {/* Rollback */}
                {step.rollback_action && (
                  <div className="flex items-center gap-1 text-[10px] text-gray-700 mt-0.5">
                    <RotateCcw size={9} className="shrink-0" />
                    <span className="truncate">{step.rollback_action}</span>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )
      })}
    </div>
  )
}
